### ISSUE TITLE
It would be cool to have quotes translatable(to English at least)

### ISSUE THREAD

**Issue by wolendranh** [GerbenAaltink/slack-quote#12]
Sometimes you can feel lonely and unprotected when you don't understand Dutch and people are posting quotes that you don't get sense of

**Comment by Gilandor** [comment]
Would add that adding an extra field can allow quotes to be translated, though it'd need be manually translated.

Would add that I could.

**Comment by GerbenAaltink** [comment]
@Gilandor so your preference is to add English-field and make that one default if available?

**Comment by Gilandor** [comment]
Not sure if that is preference, check with @wolendranh for preferences and weigh them against other stakeholders : p

**Comment by Gilandor** [comment]
(Personally would prefer internationalization of bloody everything)

**Comment by wolendranh** [comment]
I think English is fine enough. But! machine translation could remove some sense from Quotes. You know...like badly translated American movie

**Comment by Gilandor** [comment]
That's my point - so, you'll need a contextual translation, that's manual work though.

Which I'm willing to do. Simply add the field in the admin.

**Comment by Gilandor** [comment]
Created pull request for this with added changes.

**Comment by GerbenAaltink** [comment]
Made by @Gilandor  :) Thanks!
