### ISSUE TITLE
Unset English as default language

### ISSUE THREAD

**Issue by GerbenAaltink** [GerbenAaltink/slack-quote#27]
Stakeholders are not happy with English translation as default value to be returned as quote. 

Therefor; this has to be developed:
 - only return translation when --english parameter is set

**Comment by GerbenAaltink** [comment]
Above solution is implemented and deployed. Also, tiles are generated in native language and English. 

So /quote pony --english will give:
 - English text 
 - English context
 - English tile 

* only if available.

**Comment by wolendranh** [comment]
Sounds complicated but - is that possible to:
`/quote`
this gives original quote text
and then If I want to translate current quote do something like
`/quote --english --previous`

Would be cool(at least for me :D)

**Comment by GerbenAaltink** [comment]
@wolendranh not complicated at all :) We already have a `next()` function, so `previous()` would not be an issue. Also we store the date when a quote is returned for the last time.

**Comment by GerbenAaltink** [comment]
@wolendranh i developed this in air plane special for you ;)

**Comment by Gilandor** [comment]
Funny, that's how I came to do #12.

**Comment by GerbenAaltink** [comment]
@Gilandor funny. This works crashes: /quote --english. But /quote --english --previous works :D
